config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'
  resources :notes
  devise_for :users
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.where("user_id = ?", current_user)
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	ALERT_TYPES = [:danger, :info, :success, :warning] unless const_defined?(:ALERT_TYPES)

	def bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type.to_s ==  :notice.to_s
      type = :danger   if type.to_s == :error.to_s
      type = :info   if type.to_s == :info.to_s
      type = :warning  if type.to_s == :alert.to_s

      next unless ALERT_TYPES.include?(type)

      Array(message).each do |msg|
        text = content_tag(:div,
                           content_tag(:button, raw("&times;"), :class => "close", "data-dismiss" => "alert") +
                           msg, :class => "alert fade in alert-#{type}")
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Mis notas</title>  
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2">
				<%= bootstrap_flash %>
				<%= yield %>
			</div>
		</div>
		<% if user_signed_in? %>
			<div class="row">
				<div class="col-lg-8 col-lg-offset-2">
					<ul class="list-inline pull-right">	                       
		        <li>
		          <%= link_to destroy_user_session_path, method: :delete do %>
		            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Salir
		          <% end %>
		        </li>
	      	</ul>
				</div>
			</div>
		<% end %>
	</div>
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for @note do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, "Título" %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description, "Descripción" %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Agregar", class: "btn btn-default" %>
<% end %>

app/views/notes/edit.html.erb
<h1>Editar nota</h1>

<%= render 'form' %>

<%= link_to 'Ver notas', @note %> |
<%= link_to 'Atras', notes_path %>

app/views/notes/index.html.erb
<h1>Mis notas</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.description %></td>
        <td><%= link_to 'Ver', note %></td>
        <td><%= link_to 'Editar', edit_note_path(note) %></td>
        <td><%= link_to 'Eliminar', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar nota', new_note_path %>

app/views/notes/new.html.erb
<h1>Agregar nota</h1>

<%= render 'form' %>

<%= link_to 'Atras', notes_path %>

app/views/notes/show.html.erb
<h1>Nota del <span class"note_date"><%= @note.created_at.to_date %></span></h1>
<p>
  <label>Título:</label>
  <%= @note.title %>
</p>

<p>
  <label>Descripción:</label>
  <%= @note.description %>
</p>

<%= link_to 'Editar', edit_note_path(@note) %> |
<%= link_to 'Atras', notes_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar sesión", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Crear cuenta", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "¿Olvidó su Contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>